### ISSUE TITLE
异形屏适配(iphonex/xr/xs)

### ISSUE THREAD

**Issue by KirinHuang** [KirinHuang/blog#7]
异形屏安全区域
![image](https://user-images.githubusercontent.com/5568561/56714358-29ace580-6767-11e9-92dd-f55d66f76593.png)

![image](https://user-images.githubusercontent.com/5568561/56714919-c9b73e80-6768-11e9-916b-955912acd977.png)

1. viewport-fit
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
```

2. safari 引入的`constant`、`env`
1.只有设置了 viewport-fit=cover，才能使用 env()
2.Webkit在iOS11中新增CSS Functions: env( )替代constant( )，文档中推荐使用env( )，而 constant( ) 从Safari Techology Preview 41 和iOS11.2 Beta开始会被弃用。
```css
.device-iphonex {
    padding-top: env(safe-area-inset-top);
    padding-right: env(safe-area-inset-right);
    padding-bottom: env(safe-area-inset-bottom);
    padding-left: env(safe-area-inset-left);
}
```
